import { Project } from '@/types'
import { getImagePlaceholder } from '@/lib/utils'

export const projects: Project[] = [
  {
    id: 'modern-residence',
    title: 'Modern Residence',
    category: 'Residential',
    description: 'This contemporary residence nestled in the hills offers panoramic views and seamless indoor-outdoor living. The design emphasizes clean lines, natural materials, and abundant natural light.\n\nThe home features an open floor plan with floor-to-ceiling windows that frame the surrounding landscape, creating a sense of connection with nature. Sustainable elements include solar panels, rainwater harvesting, and passive cooling strategies.',
    challenges: 'The steep hillside location presented significant engineering challenges. We developed innovative foundation solutions and carefully positioned the structure to minimize environmental impact while maximizing views.\n\nAnother challenge was balancing the client\'s desire for expansive glass with energy efficiency concerns. We addressed this through high-performance glazing, strategic overhangs, and automated shading systems.',
    year: '2022',
    location: 'Los Angeles, CA',
    client: 'Private Client',
    size: '5,200 sq ft',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2074&q=80',
    ],
    awards: 'AIA Design Excellence Award 2022',
  },
  {
    id: 'urban-mixed-use',
    title: 'Urban Mixed-Use Development',
    category: 'Commercial',
    description: 'This mixed-use development revitalizes a former industrial site, creating a vibrant community hub with retail, office, and residential spaces. The design preserves elements of the site\'s industrial heritage while introducing contemporary architectural elements.\n\nThe project includes a central plaza that serves as a gathering space and venue for community events. Sustainable features include green roofs, energy-efficient systems, and rainwater management infrastructure.',
    challenges: 'Integrating new construction with existing historic structures required careful planning and preservation strategies. We worked closely with heritage consultants to ensure respectful adaptation of the industrial buildings.\n\nThe complex program requirements and need for phased construction presented logistical challenges. Our team developed a comprehensive master plan and construction sequencing strategy to minimize disruption to surrounding neighborhoods.',
    year: '2021',
    location: 'Chicago, IL',
    client: 'Urban Development Partners',
    size: '120,000 sq ft',
    imageUrl: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1577493340887-b7bfff550145?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      'https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2072&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2069&q=80',
    ],
    awards: 'Urban Land Institute Excellence Award 2021',
  },
  {
    id: 'cultural-center',
    title: 'Contemporary Art Museum',
    category: 'Cultural',
    description: 'This museum creates a dialogue between art, architecture, and the urban context. The building serves as both a container for art and an artistic statement itself, with dynamic spaces that can adapt to various exhibition needs.\n\nThe design features a series of interconnected volumes with varying scales and lighting conditions, providing curators with flexible exhibition possibilities. Public spaces encourage community engagement and offer views of the surrounding cityscape.',
    challenges: 'Creating optimal conditions for art display while achieving the client\'s vision for an iconic architectural statement required careful balance. We conducted extensive daylighting studies and developed sophisticated lighting and climate control systems.\n\nThe complex geometry of the building presented structural and construction challenges. Our team utilized advanced computational design and digital fabrication techniques to realize the ambitious forms while maintaining budget constraints.',
    year: '2020',
    location: 'Miami, FL',
    client: 'Metropolitan Arts Foundation',
    size: '75,000 sq ft',
    imageUrl: 'https://images.unsplash.com/photo-1529497584152-d0c9a6c2dc95?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2071&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1572947650440-e8a97ef053b2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      'https://images.unsplash.com/photo-1566454825481-a2a11df6c3bd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      'https://images.unsplash.com/photo-1574365569389-a10d488ca3fb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    ],
    awards: 'AIA Honor Award 2020, International Architecture Award 2021',
  },
  {
    id: 'sustainable-office',
    title: 'Sustainable Office Campus',
    category: 'Commercial',
    description: 'This corporate headquarters sets new standards for sustainable workplace design. The campus comprises multiple buildings organized around landscaped courtyards, creating a harmonious relationship between architecture and nature.\n\nThe design prioritizes occupant wellbeing with abundant natural light, biophilic elements, and spaces for collaboration and respite. The project achieved LEED Platinum certification through innovative energy systems, water conservation strategies, and responsible material selection.',
    challenges: 'Meeting the client\'s ambitious sustainability goals while creating a high-performance workplace required integrated design approaches. We assembled a multidisciplinary team and utilized performance modeling throughout the design process.\n\nThe large scale and phased implementation of the project presented coordination challenges. We developed a flexible master plan that allowed for construction in stages while maintaining operational continuity for the client.',
    year: '2019',
    location: 'Seattle, WA',
    client: 'Tech Innovations Inc.',
    size: '250,000 sq ft',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2069&q=80',
    ],
    awards: 'LEED Platinum Certification, AIA COTE Top Ten Award',
  },
  {
    id: 'urban-renewal',
    title: 'Urban Park & Community Center',
    category: 'Public',
    description: 'This project transforms a neglected urban site into a vibrant public park and community center. The design creates a series of interconnected outdoor spaces for recreation, events, and relaxation, complemented by a multipurpose facility that houses community programs.\n\nThe architecture of the community center is characterized by transparency and openness, with flexible spaces that can accommodate diverse activities. Sustainable landscape design incorporates native plantings, stormwater management features, and habitat restoration.',
    challenges: 'Remediating the brownfield site required extensive environmental assessment and innovative cleanup strategies. We worked with environmental consultants to implement phytoremediation and other sustainable approaches.\n\nEngaging diverse community stakeholders and balancing varied needs presented social challenges. Our team conducted extensive community workshops and participatory design sessions to ensure the project reflected local priorities and cultural values.',
    year: '2021',
    location: 'Philadelphia, PA',
    client: 'City of Philadelphia',
    size: '12 acres',
    imageUrl: 'https://images.unsplash.com/photo-1533659124865-d6072dc035e1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2071&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1575403071235-5dcd06cbf169?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      'https://images.unsplash.com/photo-1517457210348-703079e57d4b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      'https://images.unsplash.com/photo-1521747116042-5a810fda9664?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    ],
    awards: 'ASLA Design Excellence Award, Urban Land Institute Impact Award',
  },
  {
    id: 'mountain-retreat',
    title: 'Mountain Retreat',
    category: 'Residential',
    description: 'This mountain retreat offers a contemporary interpretation of alpine architecture. The design responds to the dramatic landscape with a series of pavilions that frame views and create sheltered outdoor spaces for enjoying the natural setting in all seasons.\n\nMaterials were selected for their durability, contextual appropriateness, and minimal environmental impact. The project employs passive heating and cooling strategies tailored to the mountain climate, significantly reducing energy consumption.',
    challenges: 'The remote location and extreme climate conditions presented logistical and technical challenges. We developed construction strategies that accommodated the short building season and difficult site access.\n\nIntegrating the building into the sensitive alpine ecosystem required careful site planning. Our team conducted thorough environmental assessments and designed the structure to minimize disruption to natural drainage patterns and wildlife habitats.',
    year: '2020',
    location: 'Aspen, CO',
    client: 'Private Client',
    size: '4,800 sq ft',
    imageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2065&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1505843513577-22bb7d21e455?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2069&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2074&q=80',
      'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2071&q=80',
    ],
  },
  {
    id: 'education-campus',
    title: 'Innovation Education Campus',
    category: 'Educational',
    description: 'This educational facility reimagines learning environments for the 21st century. The campus comprises interconnected buildings organized around a central commons, with specialized facilities for various disciplines and flexible spaces that support collaborative, project-based learning.\n\nThe design emphasizes transparency, allowing visibility between different learning activities and creating a sense of community. Outdoor learning spaces extend the educational environment beyond the buildings, taking advantage of the temperate climate.',
    challenges: 'Balancing the client\'s forward-thinking educational philosophy with practical considerations of budget and maintenance required creative solutions. We worked closely with educators to develop innovative yet durable design strategies.\n\nCoordinating complex building systems while maintaining the desired aesthetic of openness and transparency presented technical challenges. Our integrated design team developed coordinated solutions that elegantly incorporated structural, mechanical, and technological requirements.',
    year: '2019',
    location: 'Austin, TX',
    client: 'Regional School District',
    size: '185,000 sq ft',
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2086&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2069&q=80',
      'https://images.unsplash.com/photo-1522661067900-ab829854a57f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2022&q=80',
    ],
    awards: 'AIA Educational Facility Design Award, Learning By Design Outstanding Project',
  },
  {
    id: 'waterfront-hotel',
    title: 'Waterfront Boutique Hotel',
    category: 'Hospitality',
    description: 'This boutique hotel creates a distinctive hospitality experience that celebrates its waterfront location. The design balances luxury with environmental sensitivity, offering guests immersive connections to the surrounding landscape and water.\n\nThe architecture is characterized by a series of pavilions that step down toward the water, with guest rooms and public spaces oriented to maximize views. Materials and details draw inspiration from maritime traditions while expressing a contemporary aesthetic.',
    challenges: 'Designing for a sensitive coastal site required careful environmental planning and compliance with stringent regulations. We worked with coastal engineers and environmental consultants to develop sustainable strategies for building in this context.\n\nCreating a luxury experience while adhering to principles of environmental responsibility presented conceptual challenges. Our design team developed innovative approaches that redefined luxury through authenticity, connection to place, and thoughtful detailing rather than excessive consumption.',
    year: '2021',
    location: 'Portland, ME',
    client: 'Coastal Hospitality Group',
    size: '65,000 sq ft',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      'https://images.unsplash.com/photo-1611892440504-42a792e24d32?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
      'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2071&q=80',
    ],
    awards: 'Travel + Leisure Design Award',
  }
]